# Generated by Django 4.0.1 on 2022-03-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0002_extenduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='ExtendUser',
        ),
    ]
