# Generated by Django 4.0.1 on 2022-05-05 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_remove_player_player_email'),
        ('matchs', '0005_alter_matchs_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.player'),
        ),
    ]
